// <auto-generated />
using System;
using CitaFacil.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CitaFacil.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251117213046_RemoveDoctorTelefono")]
    partial class RemoveDoctorTelefono
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CitaFacil.Models.Cita", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime?>("actualizada_el")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("creada_el")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("doctor_id")
                        .HasColumnType("bigint");

                    b.Property<int>("duracion_minutos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(30);

                    b.Property<bool>("es_virtual")
                        .HasColumnType("bit");

                    b.Property<string>("estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("PENDIENTE");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("hora")
                        .HasColumnType("time");

                    b.Property<string>("motivo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("notas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("paciente_id")
                        .HasColumnType("bigint");

                    b.Property<string>("ubicacion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("id");

                    b.HasIndex("doctor_id");

                    b.HasIndex("paciente_id");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("CitaFacil.Models.Doctor", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("biografia")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("consultorio")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("especialidad_id")
                        .HasColumnType("bigint");

                    b.Property<string>("licencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("segundo_apellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("usuario_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("especialidad_id");

                    b.HasIndex("licencia")
                        .IsUnique();

                    b.HasIndex("usuario_id")
                        .IsUnique();

                    b.ToTable("Doctores");
                });

            modelBuilder.Entity("CitaFacil.Models.Especialidad", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<bool>("activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("icono")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("CitaFacil.Models.Notificacion", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("asunto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<long>("doctor_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("enviada_el")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("leida")
                        .HasColumnType("bit");

                    b.Property<string>("mensaje")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("paciente_id")
                        .HasColumnType("bigint");

                    b.Property<bool>("via_sistema")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("doctor_id");

                    b.HasIndex("paciente_id");

                    b.ToTable("notificaciones", (string)null);
                });

            modelBuilder.Entity("CitaFacil.Models.Paciente", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("direccion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("fecha_nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("genero")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("segundo_apellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("usuario_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("usuario_id")
                        .IsUnique();

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("CitaFacil.Models.Usuario", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<bool>("activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("apellido")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("celular")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("contraseña")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("creado_el")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("foto_url")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("id");

                    b.HasIndex("correo")
                        .IsUnique();

                    b.HasIndex("usuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CitaFacil.Models.Cita", b =>
                {
                    b.HasOne("CitaFacil.Models.Doctor", "Doctor")
                        .WithMany("Citas")
                        .HasForeignKey("doctor_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CitaFacil.Models.Paciente", "Paciente")
                        .WithMany("Citas")
                        .HasForeignKey("paciente_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("CitaFacil.Models.Doctor", b =>
                {
                    b.HasOne("CitaFacil.Models.Especialidad", "Especialidad")
                        .WithMany("Doctores")
                        .HasForeignKey("especialidad_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CitaFacil.Models.Usuario", "Usuario")
                        .WithOne("Doctor")
                        .HasForeignKey("CitaFacil.Models.Doctor", "usuario_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CitaFacil.Models.Notificacion", b =>
                {
                    b.HasOne("CitaFacil.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("doctor_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CitaFacil.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("paciente_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("CitaFacil.Models.Paciente", b =>
                {
                    b.HasOne("CitaFacil.Models.Usuario", "Usuario")
                        .WithOne("Paciente")
                        .HasForeignKey("CitaFacil.Models.Paciente", "usuario_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CitaFacil.Models.Doctor", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("CitaFacil.Models.Especialidad", b =>
                {
                    b.Navigation("Doctores");
                });

            modelBuilder.Entity("CitaFacil.Models.Paciente", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("CitaFacil.Models.Usuario", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("Paciente");
                });
#pragma warning restore 612, 618
        }
    }
}
